slangs_dict = {
    '$': ' dollar ',
    '€': ' euro ',
    'abt': 'about',
    'bout': 'about',
    'abt2': 'about to',
    'bc': 'abuse',
    'mc': 'abuse',
    'acct': 'account',
    'ack': 'acknowledged',
    'alol': 'actually laughing out loud',
    'admin': 'administrator',
    'p.m': 'after midday',
    'asl': 'age, sex, location',
    'aggro': 'aggression',
    'ac': 'air conditioning',
    'ight': 'alright',
    'aka': 'also known as',
    'awl': 'always with love',
    'amazn': 'amazing',
    'ammo': 'ammunition',
    'nd': 'and',
    'etc': 'and so on',
    'agl': 'angel',
    'anon': 'anonymous',
    'adih': 'another day in hell',
    'ne': 'any',
    'nemore': 'anymore',
    'ne1': 'anyone',
    'ne1er': 'anyone here',
    'a3': 'anytime anywhere anyplace',
    'neway': 'anyway',
    'newaze': 'anyways',
    'app': 'application',
    'apps': 'applications',
    'approx': 'approximately',
    'r': 'are',
    'ru': 'are you',
    'ruc': 'are you coming?',
    'aymm': 'are you my mother',
    'ruok': 'are you ok',
    'rut': 'are you there?',
    'rnt': "aren't",
    'ai': 'artificial intelligence',
    'aamof': 'as a matter of fact',
    'afaic': 'as far as i am concerned',
    'afaict': 'as far as i can tell',
    'afaik': 'as far as i know',
    'afair': 'as far as i remember',
    'aiic': 'as if i care',
    'alap': 'as long as possible',
    'amap': 'as much as possible',
    'asat': 'as simple as that',
    'asap': 'as soon as possible',
    'ayk': 'as you know',
    'ama': 'ask me anything',
    'ams': 'ask me something',
    'atk': 'at the keyboard',
    'ayor': 'at your own risk',
    'tude': 'attitude',
    'hottie': 'attractive person',
    'mojo': 'attractive talent',
    'ave.': 'avenue',
    'afk': 'away from keyboard',
    'awsm': 'awesome',
    'azm': 'awesome',
    'awks': 'awkward',
    'bk': 'back',
    'bak': 'back at keyboard',
    'b@u': 'back at you',
    'bo': 'back off',
    'siv': 'bad goaltender',
    'hoops': 'basketball',
    'b': 'be',
    'bbias': 'be back in a second',
    'bbl': 'be back later',
    'bbs': 'be back soon',
    'brb': 'be right back',
    'brt': 'be right there',
    'bcoz': 'because',
    'bcos': 'because',
    'bcz': 'because',
    'b&b': 'bed and breakfast',
    'b+b': 'bed and breakfast',
    'b4': 'before',
    'be4': 'before',
    'bae': 'before anyone else',
    'b.c': 'before christ',
    'a.m': 'before midday',
    'bff': 'best friends forever',
    'btwn': 'between',
    'bsaaw': 'big smile and a wink',
    'b-day': 'birthday',
    'bday': 'birthday',
    'b&w': 'black and white',
    'bcc': 'blind carbon copy',
    'blvd': 'boulevard',
    'bf': 'boyfriend',
    'bbc': 'british broadcasting corporation',
    'bro': 'brother',
    'bros': 'brothers',
    'bwl': 'bursting with laughter',
    'biz': 'business',
    'b2b': 'business to business',
    'b2c': 'business to customer',
    'btw': 'by the way',
    'bai': 'bye',
    'bb': 'bye bye',
    'bbbg': 'bye bye be good',
    'b4n': 'bye for now',
    'bfn': 'bye for now',
    'cyb': 'call you back',
    'csl': 'can not stop laughing',
    'c/o': 'care of',
    'cyl': 'catch ya later',
    'cet': 'central european time',
    'cia': 'central intelligence agency',
    'char': 'character',
    'cye': 'check your e-mail',
    'cyf': 'check your facebook',
    'cyfb': 'check your facebook',
    'cym': 'check your myspace',
    'moss': 'chill',
    'combo': 'combination',
    'cf': 'compare',
    'cwot': 'complete waste of time',
    'ownage': 'completely owned',
    'grats': 'congratulations',
    'gratz': 'congratulations',
    'kewl': 'cool',
    'kwl': 'cool',
    'utc': 'coordinated universal time',
    'waa': 'crying',
    'cv': 'curriculum vitae',
    'kewt': 'cute',
    'qt': 'cutie',
    'qtpi': 'cutie pie',
    'd8': 'date',
    'dob': 'date of birth',
    'ded': 'dead',
    'dece': 'decent',
    'dept': 'department',
    'dm': 'direct message',
    'diy': 'do it yourself',
    'dbmib': 'do not bother me i am busy',
    'dnd': 'do not disturb',
    'dae': 'does anyone else',
    'dnt': "don't",
    'dk': "don't know",
    'dno': "don't know",
    'dlm': "don't leave me",
    'dwh': 'during work hours',
    'embm': 'early morning business meeting',
    'eet': 'eastern european time',
    'e123': 'easy as one two three',
    'emo': 'emotional',
    'encl': 'enclosed',
    'encl.': 'enclosed',
    'eod': 'end of discussion',
    'eof': 'end of file',
    'eom': 'end of message',
    'enuf': 'enough',
    'nuff': 'enough',
    'eta': 'estimated time of arrival',
    'e1': 'everyone',
    'every1': 'everyone',
    'eg': 'example',
    'exp': 'experience',
    'fab': 'fabulous',
    'f2f': 'face to face',
    'fb': 'facebook',
    'fbc': 'facebook chat',
    'fbf': 'facebook friend',
    'fail': 'failure',
    'fml': 'family',
    'fav': 'favorite',
    'fave': 'favorite',
    'favs': 'favorites',
    'ft': 'featuring',
    'ft.': 'feet',
    'f': 'female',
    'fig': 'figure',
    'f9': 'fine',
    'fn': 'fine',
    'fc': 'fingers crossed',
    '4ao': 'for adults only',
    'fawc': 'for anyone who cares',
    'ftl': 'for the loss',
    'ftw': 'for the win',
    'fwiw': 'for what it is worth',
    'fyi': 'for your information',
    'fimh': 'forever in my heart',
    'fo': 'freaking out',
    'f2p': 'free to play',
    'f2t': 'free to talk',
    'faq': 'frequently asked questions',
    'fri': 'friday',
    'frnd': 'friend',
    'frm': 'from',
    'fu': 'fuck you',
    'fugly': 'fucking ugly',
    'gcse': 'general certificate of secondary education',
    'emc2': 'genius',
    'g9': 'genius',
    'gahoy': 'get a hold of yourself',
    'gal': 'get a life',
    'goi': 'get over it',
    'grl': 'girl',
    'gyal': 'girl',
    'gf': 'girlfriend',
    'gv': 'give',
    'gvn': 'given',
    'gps': 'global positioning system',
    'ga': 'go ahead',
    'g4i': 'go for it',
    'gonna': 'going to',
    'g2b': 'going to bed',
    'gfn': 'gone for now',
    'gud': 'good',
    'ge': 'good evening',
    'g4n': 'good for nothing',
    'g4u': 'good for you',
    'gg': 'good game',
    'gl': 'good luck',
    'glhf': 'good luck have fun',
    'gm': 'good morning',
    'gn': 'good night',
    'g1': 'good one',
    'g2g': 'good to go',
    'gtg': 'good to go',
    'g2cu': 'good to see you',
    'gw': 'good work',
    'gorge': 'gorgeous',
    'gt2t': 'got time to talk',
    'gr8': 'great',
    'gmta': 'great minds think alike',
    'g.o.a.t': 'greatest of all time',
    'goat': 'greatest of all time',
    'gmt': 'greenwich mean time',
    'h4x0r': 'hacker',
    'haxor': 'hacker',
    'h4x0rz': 'hackers',
    'hax': 'hacks',
    'hof': 'hall of fame',
    'hbbd': 'happy belated birthday',
    'hbd': 'happy birthday',
    'hb2u': 'happy birthday to you',
    'hxc': 'hardcore',
    'h/t': 'hat tip',
    'h8': 'hate',
    'h8t': 'hate',
    'h8r': 'hater',
    'hav': 'have',
    'hf': 'have fun',
    'ht': 'height',
    'hwp': 'height weight proportionate',
    'ha': 'hello again',
    'hwu': "hey, what's up?",
    'hai': 'hi',
    'oiy': 'hi',
    'yo': 'hi',
    'rehi': 'hi again',
    'hi5': 'high five',
    'hrh': 'his royal highness',
    'hom': 'hit or miss',
    'h/o': 'hold on',
    'ho': 'hold on',
    'h/p': 'hold please',
    'holla': 'holler',
    'hwk': 'homework',
    'h/u': 'hook up',
    'h^': 'hook up',
    'hih': 'hope it helps',
    'h2cus': 'hope to see you soon',
    'hp': 'horsepower',
    'h&c': 'hot and cold',
    'h4u': 'hot for you',
    'hr': 'hour',
    'hoc': 'house of cards',
    'han': 'how about now?',
    'hay': 'how are you',
    'hru': 'how are you',
    'hc': 'how cool',
    'hcit': 'how cool is that',
    'hig': "how's it going?",
    'hak': 'hugs and kisses',
    'hry': 'hurry',
    'hubby': 'husband',
    'ia': 'i agree',
    'iail': 'i am in love',
    'i8': 'i ate',
    'idc': 'i do not care',
    'idgadf': 'i do not give a damn fuck',
    'idgaf': 'i do not give a fuck',
    'idk': 'i do not know',
    'idnk': 'i do not know',
    'idn': "i don't know",
    'idky': "i don't know why",
    'idr': "i don't remember",
    'idt': "i don't think",
    'idts': "i don't think so",
    'idu': "i don't understand",
    'idi': 'i doubt it',
    'ifyp': 'i feel your pain',
    'igi': 'i get it',
    'igtp': 'i get the point',
    'ig2p': 'i got to pee',
    'i8u': 'i hate you',
    'ih8u': 'i hate you',
    'ihu': 'i hate you',
    'ihy': 'i hate you',
    'ik': 'i know',
    'ikhyf': 'i know how you feel',
    'ikwum': 'i know what you mean',
    'ikwym': 'i know what you mean',
    'ikyd': 'i know you did',
    'ikr': 'i know, right?',
    'iyq': 'i like you',
    'ilu': 'i love you',
    'k3u': 'i love you',
    'ily': 'i love you',
    'ilub': 'i love you baby',
    'ilyl': 'i love you lots',
    'ilysm': 'i love you so much',
    'ilu2': 'i love you too',
    'imy': 'i miss you',
    'imu': 'i miss you',
    'irdk': "i really don't know",
    'ic': 'i see',
    'icq': 'i seek you',
    'ibrb': 'i will be right back',
    'idmb': "i'll do my best",
    'idtt': "i'll drink to that",
    'ilyk': "i'll let you know",
    'ima': "i'm",
    'imma': "i'm gonna",
    'ii': "i'm impressed",
    'iit': "i'm impressed too",
    'goon': 'idiot',
    'id10t': 'idiot',
    'iiok': 'if i only knew',
    'iir': 'if i remember',
    'iirc': 'if i remember correctly',
    'iiuc': 'if i understand correctly',
    'iggy': 'ignored',
    'iab': 'in a bit',
    'iagw': 'in a good way',
    'iam': 'in a minute',
    'iac': 'in any case',
    'iae': 'in any event',
    'inb4': 'in before',
    'icymi': 'in case you missed it',
    'imho': 'in my humble opinion',
    'imo': 'in my opinion',
    'iow': 'in other words',
    'irl': 'in real life',
    'ir': 'in room',
    'iyo': 'in your opinion',
    'ign': 'in-game name',
    'inc': 'incoming',
    'idd': 'indeed',
    'indie': 'independent',
    'nark': 'informant',
    'info': 'information',
    'ipo': 'initial public offering',
    'init': 'initialize',
    'IG': 'instagram',
    'ir8': 'irate',
    'iad': 'it all depends',
    'iag': "it's all good",
    'joshing': 'joking',
    'jas': 'just a second',
    'jb/c': 'just because',
    'j4f': 'just for fun',
    'j4g': 'just for grins',
    'jic': 'just in case',
    'j/k': 'just kidding',
    'jk': 'just kidding',
    'j/p': 'just playing',
    'jsyk': 'just so you know',
    'j2lyk': 'just to let you know',
    'j/w': 'just wondering',
    'kfc': 'kentucky fried chicken',
    'kinda': 'kind of',
    'muah': 'kiss',
    'mwa': 'kiss',
    'mwah': 'kiss',
    'smooch': 'kiss',
    'km': 'kiss me',
    'kma': 'kiss my ass',
    'kw': 'know',
    'kl': 'kool',
    'kek': 'korean laugh',
    'keke': 'korean laugh',
    'lamer': 'lame person',
    'l8': 'late',
    'l8er': 'later',
    'l8r': 'later',
    'ltr': 'later',
    'laf': 'laugh',
    'lmao': 'laugh my ass off',
    'lmfao': 'laugh my fucking ass off',
    'lolz': 'laugh out louds',
    'haha': 'laughing',
    'hehe': 'laughing',
    'laffing': 'laughing',
    'rof': 'laughing',
    'roflmao': 'laughing',
    'rolf': 'laughing',
    'la': 'laughing a lot',
    'lmho': 'laughing my head off',
    'loi': 'laughing on the inside',
    'kik': 'laughing out loud',
    'lol': 'laughing out loud',
    'l2p': 'learn to play',
    'lam': 'leave a message',
    'l33t': 'leet',
    'legit': 'legitimate',
    'lemeno': 'let me know',
    'lyk': 'let you know',
    'lk': 'like',
    'ltd': 'limited',
    'l2m': 'listening to music',
    'llol': 'literally laughing out loud',
    'lil': 'little',
    'lulz': 'lol',
    'ldr': 'long distance relationship',
    'ltns': 'long time no see',
    'qqn': 'looking',
    'luzr': 'loser',
    'lolol': 'lots of laugh out louds',
    'luv': 'love',
    'lv': 'love',
    'lafs': 'love at first sight',
    'lola': 'love often, laugh a lot',
    'ly': 'love ya',
    'lya': 'love you always',
    'lysm': 'love you so much',
    'lyn': 'lying',
    'md@u': 'mad at you',
    'm': 'male',
    'mng': 'manage',
    'mgmt': 'management',
    'mngr': 'manager',
    'm8': 'mate',
    'mcd': "mcdonald's",
    'mcds': "mcdonald's",
    'me2': 'me too',
    'mu@': 'meet you at',
    'mtg': 'meeting',
    'msg': 'message',
    'mid': 'middle',
    'mph': 'miles per hour',
    'notch': 'minecraft creator',
    'min': 'minute',
    'mins': 'minutes',
    'ms': 'miss',
    'mu': 'miss you',
    'mr': 'mister',
    'mod': 'modification',
    'mula': 'money',
    'mth': 'month',
    'mfb': 'mother fucking bitch',
    'mil': 'mother-in-law',
    'mf': 'motherfucker',
    'mofo': 'motherfucker',
    'mfs': 'motherfuckers',
    'mms': 'multimedia messaging service',
    'mfw': 'my face when',
    'mrw': 'my reaction when',
    'mte': 'my thoughts exactly',
    'n8kd': 'naked',
    'nbc': 'national broadcasting company',
    'nhs': 'national health service',
    'nal': 'nationality',
    'hood': 'neighborhood',
    'neva': 'never',
    'nvr': 'never',
    'n/m': 'nevermind',
    'nvm': 'nevermind',
    'nvrm': 'nevermind',
    'nyc': 'new york city',
    'n00b': 'newbie',
    'newb': 'newbie',
    'noob': 'newbie',
    'nub': 'newbie',
    'nxt': 'next',
    'n1': 'nice one',
    'nth': 'nice to have',
    'nite': 'night',
    'n64': 'nintendo 64',
    'nah': 'no',
    'naw': 'no',
    'neh': 'no',
    'nbjf': 'no brag, just fact',
    'nnto': 'no need to open',
    'nn2r': 'no need to reply',
    'nntr': 'no need to reply',
    'no1': 'no one',
    'n1c': 'no one cares',
    'np': 'no problem',
    'nrn': 'no reply necessary',
    'n/r': 'no reserve',
    'nw': 'no way',
    'nac': 'not a chance',
    'nagi': 'not a good idea',
    'nb': 'not bad',
    'nbd': 'not big deal',
    'nfs': 'not for sale',
    'ngl': 'not going to lie',
    'nnito': 'not necessarily in that order',
    'nsfl': 'not safe for life',
    'nsfw': 'not safe for work',
    'n2w': 'not to worry',
    'n2m': 'not too much',
    'n2mh': 'not too much here',
    'nufn': 'nothing',
    'n/m/h': 'nothing much here',
    'obv': 'obviously',
    'obvi': 'obviously',
    'oic': 'oh i see',
    'omg': 'oh my god',
    'ohemgee': 'oh my gosh',
    'onoz': 'oh no',
    'orly': 'oh really',
    'obtw': 'oh, by the way',
    'oicn': 'oh, i see now',
    'k': 'ok',
    'kk': 'ok',
    'mkay': 'ok',
    'mmk': 'ok',
    'yupz': 'ok',
    'kgo': 'ok, go',
    'knp': 'ok, no problem',
    'mk': 'okay',
    'otay': 'okay',
    'omw': 'on my way',
    'otw': 'on the way',
    'onl': 'online',
    'o4u': 'only for you',
    'og': 'original',
    'oc': 'original content',
    'outta': 'out of',
    'omdb': 'over my dead body',
    'ohp': 'overhead projector',
    'ovie': 'overlord',
    'pwnd': 'owned',
    'pwned': 'owned',
    'pwnt': 'owned',
    'pp': 'pages',
    'p911': 'parent alert!',
    'rents': 'parents',
    'prw': 'parents are watching',
    'p@h': 'parents at home',
    'pwd': 'password',
    'psd': 'password',
    'pswd': 'password',
    'ppp': 'peace',
    'ppl': 'people',
    'poc': 'people of color',
    'p.a': 'per annum',
    'p/d': 'per day',
    'p/m': 'per month',
    'p/y': 'per year',
    'pc': 'personal computer',
    'pic': 'picture',
    'pl8': 'plate',
    'pld': 'played',
    'ps2': 'playstation 2',
    'ps3': 'playstation 3',
    'psp': 'playstation portable',
    'pls': 'please',
    'plz': 'please',
    'plzrd': 'please read',
    'ptm': 'please tell me',
    'ptb': 'please text back',
    'pto': 'please turn over',
    'pt': 'point',
    'pov': 'point of view',
    'pj': 'poor joke',
    'ps': 'postscript',
    'lb': 'pound',
    'lbs': 'pounds',
    'rx': 'prescription',
    'pm': 'prime minister',
    'prvt': 'private',
    'prolly': 'probably',
    'prof': 'professor',
    'promo': 'promotion',
    'prot': 'protection',
    'pda': 'public display of affection',
    'psa': 'public service announcement',
    'psog': 'pure stroke of genius',
    'q4u': 'question for you',
    'qq': 'quick question',
    'qrg': 'quick reference guide',
    'qfe': 'quoted for emphasis',
    'qft': 'quoted for truth',
    'r8': 'rate',
    'rbtl': 'read between the lines',
    'rdy': 'ready',
    'rl': 'real life',
    'rlrt': 'real life retweet',
    'rly': 'really',
    'props': 'recognition',
    'rgd': 'regard',
    'rgds': 'regards',
    're': 'replay',
    'rep': 'reputation',
    'resq': 'rescue',
    'rip': 'rest in peace',
    'rt': 'retweet',
    'ridic': 'ridiculous',
    'rofl': 'rolling on the floor laughing',
    'rotflmao': 'rolling on the floor laughing my ass off',
    'roflol': 'rolling on the floor laughing out loud',
    'rm': 'room',
    'ratchet': 'rude',
    'diva': 'rude woman',
    'rn': 'run',
    'sfw': 'safe for work',
    'ditto': 'same',
    'ssdd': 'same stuff different day',
    's2u': 'same to you',
    'kappa': 'sarcasm',
    'sec': 'second',
    'c': 'see',
    'cu': 'see you',
    'cya': 'see you',
    'cyal8r': 'see you later',
    'siul8r': 'see you later',
    'syl': 'see you later',
    'cul8r': 'see you later',
    'cyo': 'see you online',
    'cu2mr': 'see you tomorrow',
    'cyt': 'see you tomorrow',
    'cu2': 'see you too',
    's2r': 'send to receive',
    'srs': 'serious',
    'srsly': 'seriously',
    'smh': 'shake my head',
    's/u': 'shut up',
    'sh^': 'shut up',
    'sk8': 'skate',
    'sk8r': 'skater',
    'zzz': 'sleeping bored and tired',
    'smf': 'so much fun',
    's/w': 'software',
    's/o': 'sold out',
    'ace': 'solo winner',
    'srry': 'sorry',
    'sry': 'sorry',
    's2s': 'sorry to say',
    'sorta': 'sort of',
    'spk': 'speak',
    'spkr': 'speaker',
    'spec': 'specialization',
    'sq': 'square',
    'samzd': 'still amazed',
    'sly': 'still love you',
    'str8': 'straight',
    'wack': 'strange',
    'str': 'strength',
    'stpd': 'stupid',
    'sho': 'sure',
    'sd': 'sweet dreams',
    'sync': 'synchronize',
    'tbs': 'tablespooful',
    'tbsp': 'tablespooful',
    'tc': 'take care',
    'tyt': 'take your time',
    'tlk': 'talk',
    't2m': 'talk to me',
    't2u': 'talk to you',
    'tty': 'talk to you',
    't2ul': 'talk to you later',
    't2ul8er': 'talk to you later',
    't2ul8r': 'talk to you later',
    'ttl': 'talk to you later',
    'ttul': 'talk to you later',
    'ttyl': 'talk to you later',
    'tlkin': 'talking',
    'tlking': 'talking',
    'num': 'tasty',
    'narc': 'tattle tale',
    'tl': 'tell',
    'teme': 'tell me',
    'txt': 'text',
    'txtin': 'texting',
    'tg': 'thank goodness',
    'thnq': 'thank you',
    'thx': 'thank you',
    'tq': 'thank you',
    'tu': 'thank you',
    'ty': 'thank you',
    'thks': 'thank you',
    'tyfa': 'thank you for asking',
    'tyl': 'thank you lord',
    'tym': 'thank you much',
    'tqvm': 'thank you very much',
    'tyvm': 'thank you very much',
    'tx': 'thanks',
    't4lmk': 'thanks for letting me know',
    't4p': 'thanks for posting',
    't4t': 'thanks for trade',
    'tia': 'thanks in advance',
    'tht': 'that',
    'tfw': 'that feeling when',
    'ie': 'that is',
    'i.e': 'that is',
    'da': 'the',
    'teh': 'the',
    'thr': 'there',
    'dis': 'this',
    'tho': 'though',
    'thru': 'through',
    't2go': 'time to go',
    'whipped': 'tired',
    'tbh': 'to be honest',
    'til': 'today i learned',
    'tomoz': 'tomorrow',
    'tl;dr': 'too long i did not read',
    'tldr': 'too long i did not read',
    'ttly': 'totally',
    'tru': 'true',
    'tntl': 'trying not to laugh',
    'tmb': 'tweet me back',
    'nooblord': 'ultimate newbie',
    'nottie': 'unattractive person',
    'u2u': 'up to you',
    'u/l': 'upload',
    'veggies': 'vegetables',
    'vs': 'versus',
    'vry': 'very',
    'w8': 'wait',
    'w8am': 'wait a minute',
    'w84m': 'wait for me',
    'w4u': 'wait for you',
    'w8ing': 'waiting',
    'w8n': 'waiting',
    'wan2': 'want to',
    'wannabe': 'want to be',
    'w2g': 'way to go',
    'wtg': 'way to go',
    'w2f': 'way too funny',
    'wk': 'week',
    'wknd': 'weekend',
    'wlcm': 'welcome',
    'w/b': 'welcome back',
    'wb': 'welcome back',
    'wa': 'what',
    'wat': 'what',
    'wha': 'what',
    'wht': 'what',
    'qpsa': 'what happens',
    'wassup': 'what is up',
    'wuzup': 'what is up',
    'wtf': 'what the fuck',
    'sup': "what's up",
    'wup': "what's up?",
    'evs': 'whatever',
    'meh': 'whatever',
    'w/e': 'whatever',
    'watev': 'whatever',
    'watevs': 'whatever',
    'wuf': 'where are you from',
    'wtpa': 'where the party at',
    'w2k': 'windows 2000',
    'wywh': 'wish you were here',
    'w/': 'with',
    'w/o': 'without',
    'yd': 'yard',
    'yrs': 'years',
    'ya': 'yes',
    'yeap': 'yes',
    'yep': 'yes',
    'yepperz': 'yes',
    'yesh': 'yes',
    'yup': 'yes',
    'u': 'you',
    'ygtr': 'you got that right',
    'ynk': 'you never know',
    'u-ok': 'you ok?',
    'uok': 'you ok?',
    'ut': 'you there?',
    'yt': 'you there?',
    'yt?': 'you there?',
    'u2': 'you too',
    'nooblet': 'young newbie',
    'ur': 'your',
    'yr': 'year',
    'u4e': 'yours for ever',
    'tbt': 'throwback thursday',
    'tcot': 'tactical change of topic',
    'cos': 'chief of staff'
}